Claw
Team-Optix-3749/Team-3749-2023 pull request #15
Opened 2023-02-04 21:39 UTC by KinetekEnergy

# Claw
- review pls

2023-02-04 22:26 UTC, rohinsood requested changes
The commands, subsystems, and files need some formatting and standardization changes, other than that it looks good.

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/RobotContainer.java
> +    // note that isHeld() doesn't work
this is an unecessary comment

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/utils/Constants.java
> +        public static final int setpoint = 0;
you should call this setpoint_velocity

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/commands/Clawauto.java
> +package frc.robot.commands;
delete this class if its not ready to  be tested

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/subsystems/Claw.java
> +
delete empty lines

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/commands/ClawIntakeCommand.java
> +/***
this should be above the class definition not above the imports

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/commands/ClawIntakeCommand.java
> +// Copyright (c) FIRST and other WPILib contributors.
remove these copyright comments

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/commands/ClawOuttakeCommand.java
> +/***
move these to above the class not abov ethe imports

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/commands/ClawOuttakeCommand.java
>  // Copyright (c) FIRST and other WPILib contributors.
delete these copyright coments

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/commands/ClawSimulationCommand.java
> +// Copyright (c) FIRST and other WPILib contributors.
delete these copyright comments

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/commands/ClawSimulationCommand.java
> +/***
move author comments to above the class, not to above the imports

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/commands/ClawSimulationCommand.java
> +    private CANSparkMax right_motor = new CANSparkMax(Constants.Claw.right_side, MotorType.kBrushless);
why are these in the command?

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/subsystems/Claw.java
> +/***
move to above the class, not the imports

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/subsystems/Claw.java
> +        // not sure what this is: Constants.Base.speed.set(new Double(16.90));
delete unecessary comments

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/subsystems/Claw.java
> +    PIDController claw_PID = new PIDController(Constants.Claw.claw_kP, Constants.Claw.claw_kI, Constants.Claw.claw_kD);
encapsulate this object

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/subsystems/Claw.java
> +public class Claw extends SubsystemBase {
your variables should be private and final

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/subsystems/Claw.java
> +    // averages the Encoder velocities from both left and right encoders.(gives error if method is not set to return double)
add javadoc comments

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/subsystems/ClawSim.java
> +
move author comments here

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/utils/ColorSensor.java
> +/***
delete this class if its not being used, move your author comments

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/utils/ColorSensor.Java
> +package frc.robot.utils;
why are there 2 ColorSensor.java?

2023-02-04 22:26 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/subsystems/ClawSim.java
> +/***
move author comments

2023-02-11 18:37 UTC, rohinsood approved these changes
I went and fixed your code code code regarding formatting conventions and new commands, check my commits

2023-02-11 18:37 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/commands/ClawSimulationCommand.java
> + * @author Zaddy Harkirat
mane what is this delete

2023-02-11 18:37 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/commands/ClawSimulationCommand.java
> +package frc.robot.commands;
delete unused files

2023-02-11 18:37 UTC, rohinsood commented on Team 3749 2023/src/main/java/frc/robot/subsystems/Claw.java
> +    private final RelativeEncoder left_encoder = left_motor.getEncoder();
add an empty line below this

2023-02-16 06:43 UTC, rjawesome approved these changes

2023-02-16 07:28 UTC, merged